apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
        - name: init-mysql
          image: mysql:8.0.26
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
          command:
            - bash
            - "-c"
            - |
              set -ex
              if [[ $HOSTNAME =~ -([0-9]+)$ ]]; then
                ordinal=${BASH_REMATCH[1]}
                if [[ $ordinal -eq 0 ]]; then
                  echo "[mysqld]" > /mnt/conf.d/server-id.cnf
                  echo "server-id=1" >> /mnt/conf.d/server-id.cnf
                else
                  echo "[mysqld]" > /mnt/conf.d/server-id.cnf
                  echo "server-id=$((ordinal+1))" >> /mnt/conf.d/server-id.cnf
                fi
              fi
          volumeMounts:
            - name: conf
              mountPath: /mnt/conf.d
            - name: config-map
              mountPath: /mnt/config-map
      containers:
        - name: mysql
          image: mysql:8.0.26
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          ports:
          - name: mysql
            containerPort: 3306
          volumeMounts:
            - name: data-mysql8-community
              mountPath: /var/lib/mysql
              subPath: mysql
            - name: conf
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: conf
          emptyDir: {}
        - name: config-map
          configMap:
            name: mysql
  volumeClaimTemplates:
    - metadata:
        name: data-mysql8-community
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi
